openapi: 3.1.0
info:
  title: Privacy Transaction Disclosure API
  description: |
    API specification for selective disclosure of privacy-preserving transactions
    across various protocols including Penumbra and Solana Confidential Transactions.
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: https://api.disclosure.example.com/v1
    description: Production server

paths:
  /disclose/transaction:
    post:
      summary: Disclose a single transaction
      operationId: discloseSingleTransaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DisclosureRequestSingle'
      responses:
        '200':
          description: Successfully disclosed transaction
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /disclose/transactions:
    post:
      summary: Disclose multiple transactions
      operationId: discloseMultipleTransactions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DisclosureRequestMultiple'
      responses:
        '200':
          description: Results for each disclosed transaction
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DisclosedTransactionResult'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    DisclosureRequestSingle:
      type: object
      required:
        - fullViewingKey
        - transactionHash
      properties:
        fullViewingKey:
          type: string
          description: Full viewing key used to disclose the transaction
          examples: ["penumbra1fvk..."]
        transactionHash:
          type: string
          description: Transaction hash to disclose
          examples: ["0xabc123..."]

    DisclosureRequestMultiple:
      type: object
      required:
        - fullViewingKey
        - transactionHashes
      properties:
        fullViewingKey:
          type: string
          description: Full viewing key used to disclose transactions
          examples: ["penumbra1fvk..."]
        transactionHashes:
          type: array
          items:
            type: string
          examples: [["0xabc123...", "0xdef456..."]]

    DisclosedTransactionResult:
      type: object
      properties:
        disclosureTransactions:
          type: object
          required:
            - transactions
          properties:
            transactions:
              type: array
              items:
                $ref: '#/components/schemas/Transaction'
        disclosureErrors:
          type: object
          required:
            - errors
          properties:
            errors:
              type: array
              items:
                $ref: '#/components/schemas/DisclosureError'



    Transaction:
      type: object
      required:
        - transactionHash
        - protocol
        - chainId
        - counterparties
        - timestamp
        - disclosureTypes
      properties:
        transactionHash:
          type: string
          description: Unique transaction hash/identifier
          examples: ["0x1234567890abcdef"]
        protocol:
          type: string
          enum: [penumbra, solana_confidential_transaction]
          description: Protocol used for the transaction
        chainId:
          type: string
          description: Blockchain network ID
          examples: ["1", "solana:mainnet-beta"]
        counterparties:
          type: array
          items:
            $ref: '#/components/schemas/Counterparty'
        timestamp:
          type: string
          format: date-time
        metadata:
          type: array
          items:
            $ref: '#/components/schemas/Metadata'

    DisclosureError:
      type: object
      required:
        - resultType
        - transactionHash
        - error
        - errorTypes
      properties:
        resultType:
          type: string
          enum: [error]
        transactionHash:
          type: string
        error:
          $ref: '#/components/schemas/Error'
        errorTypes:
          type: array
          description: Identifiers for the error types
          items:
            type: string
          examples: [["transaction_not_found", "invalid_fvk"]]

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Machine-readable error code
          examples: ["transaction_not_found"]
        message:
          type: string
          description: Human-readable error message
          examples: ["Transaction hash not found for given FullViewingKey."]

    Counterparty:
      type: object
      required:
        - role
        - address
        - assets
      properties:
        role:
          type: string
          enum: [sender, receiver]
        address:
          type: string
        name:
          type: string
        assets:
          type: array
          items:
            $ref: '#/components/schemas/Asset'

    Asset:
      type: object
      required:
        - identifier
        - amount
      properties:
        identifier:
          type: string
          description: Token symbol or denomination
          examples: ["USDC"]
        amount:
          type: string
          description: Value as string to preserve precision
          examples: ["100.00"]
        decimals:
          type: integer
          default: 18
          minimum: 0
          examples: [6]

    Metadata:
      type: object
      properties:
        transactionType:
          type: string
        tags:
          type: array
          items:
            type: string
        notes:
          type: string
