openapi: 3.1.0
info:
  title: Privacy Transaction Disclosure API
  description: |
    API specification for selective disclosure of privacy-preserving transactions
    across various protocols including Penumbra and Solana Confidential Transactions.
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: https://api.disclosure.example.com/v1
    description: Production server
components:
  schemas:
    Transaction:
      type: object
      required:
        - transactionHash
        - protocol
        - chainId
        - counterparties
        - timestamp
      properties:
        transactionHash:
          type: string
          description: Unique transaction hash/identifier
          examples: ["0x1234567890abcdef"]
        protocol:
          type: string
          description: Privacy protocol used (e.g., penumbra, solana)
          enum: [penumbra, solana_confidential_transaction]
        chainId:
          type: string
          description: Identifier of the blockchain where the transaction occurred
          examples: ["1", "solana:mainnet-beta", "penumbra:mainnet-v1"]
        counterparties:
          type: array
          description: Involved parties in the transaction
          items:
            $ref: '#/components/schemas/Counterparty'
        timestamp:
          type: string
          format: date-time
          description: Timestamp of the transaction
        metadata:
          type: array
          description: Optional metadata about the transaction
          items:
            $ref: '#/components/schemas/Metadata'

    Counterparty:
      type: object
      required:
        - role
        - address
        - assets
      properties:
        role:
          type: string
          enum: [sender, receiver]
          description: Role of the counterparty in the transaction
        address:
          type: string
          description: Address of the counterparty
        name:
          type: string
          description: Optional identifier or label for the counterparty
        assets:
          type: array
          description: Assets transferred by this counterparty
          items:
            $ref: '#/components/schemas/Asset'

    Asset:
      type: object
      required:
        - identifier
        - amount
      properties:
        identifier:
          type: string
          description: Asset identifier (e.g., token address, denomination)
          examples: ["USDC"]
        amount:
          type: string
          description: Amount of asset transferred (as string to preserve precision)
          examples: ["100.123"]
        decimals:
          type: integer
          description: Number of decimal places for the asset
          minimum: 0
          default: 18
          examples: [6]

    Metadata:
      type: object
      description: Optional metadata for additional transaction context
      properties:
        transactionType:
          type: string
          description: Type of transaction
        tags:
          type: array
          description: Custom tags for the transaction
          items:
            type: string
        notes:
          type: string
          description: Additional notes about the transaction

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Error code
        message:
          type: string
          description: Error message