[package]
name = "penumbra"
version = "0.1.0"
edition = "2021"

[dependencies.common]
path = "../common"

[dependencies.penumbra-sdk-view]
git = "https://github.com/penumbra-zone/penumbra"
tag = "v1.4.0"
[dependencies.penumbra-sdk-keys]
git = "https://github.com/penumbra-zone/penumbra"
tag = "v1.4.0"
[dependencies.penumbra-sdk-txhash]
git = "https://github.com/penumbra-zone/penumbra"
tag = "v1.4.0"
[dependencies.penumbra-sdk-proto]
git = "https://github.com/penumbra-zone/penumbra"
tag = "v1.4.0"
features = ["box-grpc"]

[dependencies.futures]
version = "0.3"

[dependencies.tendermint-rpc]
version = "0.40.3"

[dependencies.tonic]
version = "0.12.3"

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.anyhow]
version = "1"

[dependencies.camino]
version = "1"

[dev-dependencies.hex]
version = "0.4"