/*
 * Privacy Transaction Disclosure API
 *
 * API specification for selective disclosure of privacy-preserving transactions across various protocols including Penumbra and Solana Confidential Transactions. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Asset {
    /// Asset identifier (e.g., token address, denomination)
    #[serde(rename = "identifier")]
    pub identifier: String,
    /// Amount of asset transferred (as string to preserve precision)
    #[serde(rename = "amount")]
    pub amount: String,
    /// Number of decimal places for the asset
    #[serde(rename = "decimals", skip_serializing_if = "Option::is_none")]
    pub decimals: Option<u32>,
}

impl Asset {
    pub fn new(identifier: String, amount: String) -> Asset {
        Asset {
            identifier,
            amount,
            decimals: None,
        }
    }
}

