/*
 * Privacy Transaction Disclosure API
 *
 * API specification for selective disclosure of privacy-preserving transactions across various protocols including Penumbra and Solana Confidential Transactions.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DisclosureRequestSingle {
    /// Full viewing key used to disclose the transaction
    #[serde(rename = "fullViewingKey")]
    pub full_viewing_key: String,
    /// Transaction hash to disclose
    #[serde(rename = "transactionHash")]
    pub transaction_hash: String,
}

impl DisclosureRequestSingle {
    pub fn new(full_viewing_key: String, transaction_hash: String) -> DisclosureRequestSingle {
        DisclosureRequestSingle {
            full_viewing_key,
            transaction_hash,
        }
    }
}
