/*
 * Privacy Transaction Disclosure API
 *
 * API specification for selective disclosure of privacy-preserving transactions across various protocols including Penumbra and Solana Confidential Transactions. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@example.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Error {
    /// Error code
    #[serde(rename = "code")]
    pub code: String,
    /// Error message
    #[serde(rename = "message")]
    pub message: String,
}

impl Error {
    pub fn new(code: String, message: String) -> Error {
        Error {
            code,
            message,
        }
    }
}

